### ISSUE TITLE
Installed on Luna / Yosemite / Java 8-31 and Menu Item Doesn't Appear

### ISSUE THREAD

**Issue by robgcf** [turesheim/eclipse-utilities#5274]
Installed this on my Eclipse Luna copy, on Yosemite, with Java 8 update 31, and the menu item doesn't appear.  Log file is attached (I hope).  Edit: Nope, doesn't appear there's any way to attach a log file. WTF?  This is one of many reasons I don't like Github.  Msg me and I can email it to you.  Sigh.

**Comment by turesheim** [comment]
The simplest way is to close Eclipse. Delete the file. Start Eclipse and paste the entire contents into the comment field. That should contain only the interesting bits.

**Comment by turesheim** [comment]
Thanks for the log file Robert, I found this in the log:
```
!ENTRY no.resheim.eclipse.utils.launcher.core 4 0 2015-03-30 16:13:13.881
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: no.resheim.eclipse.utils.launcher.core [638]
  Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=1.7))"
```
This indicates that you're not running Eclipse on Java 1.7, and being on Luna you probably miss a few other features since many requires Java 1.7. My guess is that you have Java 1.8, but it is not used per default. Did you by any chance install Java 1.6 from Apple *after* you installed Java 1.8? If so, that will take precedence. And if that's the case I suggest re-installing Java 8 instead of hacking on the command line.

**Comment by turesheim** [comment]
There's a hint to improve the Eclipse platform in this: https://bugs.eclipse.org/bugs/show_bug.cgi?id=463656
